version: '3.8'

services:
  docusaurus-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - '9090:3000' # ホスト側9090 -> コンテナ側3000
      - '9091:3001' # ホスト側9091 -> コンテナ側3001
    environment:
      - NODE_ENV=development
    working_dir: /workspace
    command: sleep infinity
    user: node
