version: '3.8'

services:
  docusaurus-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /workspace/website/node_modules
    ports:
      - '8080:3000' # ホスト側8080 -> コンテナ側3000
      - '8081:3001' # ホスト側8081 -> コンテナ側3001
    environment:
      - NODE_ENV=development
    working_dir: /workspace
    command: sleep infinity
    user: node
